# Generated by Django 4.2 on 2023-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_orderdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
